---
chdir: "/home/ubuntu/project/QnA"
environment: development
address: 172.16.1.10
port: 3000
timeout: 30
log: "/home/ubuntu/project/QnA/log/thin_rails_server.log"
pid: tmp/pids/thin_rails_server.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
